[package]
name = "protocol_coordinate_mediation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
agent_core = { path = "../../core/agent_core" }
agent_events = { path = "../../core/agent_events", optional = true }
did = { path = "../../did" }
didcomm = { path = "../../didcomm" }
protocol_connections = { path = "../connections" }
protocol_pickup = { path = "../pickup" }
protocol_push_notifications = { path = "../push_notifications" }

async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
dashmap = "6"
chrono = { workspace = true }
tracing = { workspace = true }
bs58 = { workspace = true }
base64 = { workspace = true }

[features]
default = ["events"]
events = ["agent_events"]

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
